### ISSUE TITLE
Installation throws an error if you don't have `simstudy` already installed

### ISSUE THREAD

**Issue by restrellado** [data-edu/dataedu#25]
When I used `devtools::install_github("data-edu/dataedu")` I got this error: 

```
Error in library(simstudy) : there is no package called ‘simstudy’
Error: unable to load R code in package ‘dataedu’
Execution halted
```

I installed `simstudy` and that seemed to fix the problem. Is there a way we can require `simstudy` when installing the package?

**Comment by jrosen48** [comment]
I think this was addressed at the same time as #26
