### ISSUE TITLE
Installing from GitHub throws an error because `tidyverse::select` is missing

### ISSUE THREAD

**Issue by restrellado** [data-edu/dataedu#26]
Used `devtools::install_github("data-edu/dataedu")` and got this error: 

```
Error in select(s12_course_data, ) : could not find function "select"
Error: unable to load R code in package ‘dataedu’
Execution halted
```
I'm guessing `library(tidyverse)` needs to appear in a script somewhere, but not sure where.

**Comment by jrosen48** [comment]
can you try this again using the latest version of the package? I think(/hope!) this and #25 are resolved in that PR. I remember seeing these errors when building.

**Comment by ivelasq** [comment]
I often get errors with `select()` - maybe change to `dplyr::select()`?

**Comment by jrosen48** [comment]
just pushed a change to do this

**Comment by restrellado** [comment]
Awesome it works now! Thank you
