### ISSUE TITLE
R CMD check issues

### ISSUE THREAD

**Issue by gvelasq** [data-edu/dataedu#33]
Starting from the latest Travis build [#35](https://travis-ci.org/data-edu/dataedu/builds/633103873), there are several remaining items to address in `R CMD check`:

- [x] Warning: Several LaTeX errors with .Rd files ending in `\end{description}`, possibly because `@description` is meant to be the [second paragraph of each documentation block](https://roxygen2.r-lib.org/articles/rd.html). Lines:
	- [L7090](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7090)
	- [L7100](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7100)
	- [L7113](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7113)
	- [L7128](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7128)
	- [L7150](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7150)
	- [L7160](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7160)
- [x] Warning: Several LaTeX errors for 'Overfull `\hbox`'. Lines:
	- [L7122](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7122)
	- [L7137](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7128)
	- [L7141](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7141)
	- [L7145](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7145)
	- [L7170](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7170)
- [x] Error: Error in texi2dvi, unable to run ‘pdflatex’ on ‘Rd2.tex’
	- [L7319](https://travis-ci.org/data-edu/dataedu/builds/633103873#L7319) says ‘Error in running `tools::texi2pdf()`. Since [L699](https://travis-ci.org/data-edu/dataedu/builds/633103873#L699) doesn’t list {tools} as an attached base package and it’s not listed on [L825](https://travis-ci.org/data-edu/dataedu/builds/633103873#L825) as one of the 94 installed packages, we might need to add {tools} to .travis.yml.
- [x] Warning: Non-standard license specification, CCBY-4.0
- [x] Note: No visible global function definitions for several functions from [L8360](https://travis-ci.org/data-edu/dataedu/builds/633103873#L8360) to [L8375](https://travis-ci.org/data-edu/dataedu/builds/633103873#L8375)
- [x] Note: Undefined global functions or variables from [L8376](https://travis-ci.org/data-edu/dataedu/builds/633103873#L8376) to [L8378](https://travis-ci.org/data-edu/dataedu/builds/633103873#L8378)
- [x] Warning: Missing documentation entry for `wt05_aggdat_merged_dat` on [L8386](https://travis-ci.org/data-edu/dataedu/builds/633103873#L8386)
- [x] Warning: Code/documentation mismatch for `tt_tweets` on [L8394](https://travis-ci.org/data-edu/dataedu/builds/633103873#L8394)
- [x] Warning: ‘processed’ and ‘raw’ folders in the ‘data’ directory
	- Travis suggests moving these to ‘inst/extdata’

**Comment by gvelasq** [comment]
Fixed in #42

**Comment by ivelasq** [comment]
Thank you!!
