### ISSUE TITLE
minor - add date to DESCRIPTION?

### ISSUE THREAD

**Issue by jrosen48** [data-edu/dataedu#63]
just noticed this warning when generating citaitons for the packages used in the book:

``` r
knitr::write_bib(c("bookdown", "tidyverse", "dplyr", "tidyr", 
                 "ggplot2", "sjPlot", "lme4", "ggraph", "tidygraph", 
                 "caret", "readxl", "here", "lubridate", "dummies",
                 "janitor", "dataedu", "tidyverse", dataedu:::all_packages), "packages.bib")
#> Warning in citation(pkg, auto = if (pkg == "base") NULL else TRUE): no date
#> field in DESCRIPTION file of package 'dataedu'
```

<sup>Created on 2020-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ivelasq** [comment]
I found this thread: https://github.com/r-lib/devtools/issues/1327

**Comment by ivelasq** [comment]
Do you have an example of Date in the DESCRIPTION file, so I can make sure I follow the conventions right?

**Comment by jrosen48** [comment]
ahh my bad and I'm sorry, I didn't realie that was CRAN-generated!

**Comment by jrosen48** [comment]
OK, sorry on two counts, it also didn't lead to any problems in terms of generating the reference, which is:

```
@Manual{R-dataedu,
  title = {dataedu: Package for Data Science in Education Using R},
  author = {Emily Bovee and Ryan Estrellado and Jesse Mostipak and Joshua Rosenberg and Isabella Velásquez},
  year = {2020},
  note = {R package version 0.1.0},
  url = {https://github.com/data-edu/dataedu},
}
```

Closing this, sorry.
