### ISSUE TITLE
error in instalation using ... devtools::install_github("data-edu/dataedu")

### ISSUE THREAD

**Issue by suresh2014** [data-edu/dataedu#81]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r

> devtools::install_github("data-edu/dataedu")
Downloading GitHub repo data-edu/dataedu@master
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Error: Failed to install 'dataedu' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/RtmpCrd0sR/file33f81e7ec26a.tar.gz' -C '/tmp/RtmpCrd0sR/remotes33f8291625ea'’ returned error code 127
```
please solve this

**Comment by ivelasq** [comment]
Hello,

Could you please let us know if 1) you installed R using anaconda and 2) if you've taken any steps to try to solve this before posting? A Google search led me to these links. Unfortunately, it seems like it is a system environment issue, not a package issue.

* https://github.com/r-lib/devtools/issues/379
* https://github.com/r-dbi/RPostgres/issues/110

Please try `Sys.setenv(TAR = "/bin/tar")` per these posts.

If that does not work and you installed R through anaconda, [this issue](https://github.com/r-lib/devtools/issues/2101) from 29 days ago states that if you are using `conda` you need to use` conda` to install all packages. See https://whattheyforgot.org/set-up-an-r-dev-environment.html#what-about-conda for more info.

Thanks!

**Comment by ivelasq** [comment]
Hi @suresh2014, closing this but please try out my recommendations above. Hope you are able to install the package!
